server:
  port: 9999
  servlet:
    encoding:
      force: true
      charset: UTF-8

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: startfit
    password: startfit
