server:
  port: 8888
  servlet:
    encoding:
      force: true
      charset: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/START_FIT?serverTimezone=Asia/Seoul
    username: startfit
    password: startfit

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_ID}
    password: ${SEND_MALE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          # Google OAuth2 설정
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:8888/oauth2/callback/google"
            scope:
              - email
              - profile

          # Kakao OAuth2 설정
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            # 인증후 리다렉트 URL
            redirect-uri: "http://localhost:8888/oauth2/callback/kakao"
            # 인증 부여 유형
            authorization-grant-type: authorization_code
            # 인증 제공 방법
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image

          # Naver OAuth2 설정
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: "http://localhost:8888/oauth2/callback/naver"
            authorization-grant-type: authorization_code
            scope:
              - email

        # Provider 설정
        provider:
          # Kakao OAuth2 Provider 설정
          kakao:
            # 사용자 인증을 위한 URL
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            # 인증 후 토큰 제공하는 URL
            token-uri: https://kauth.kakao.com/oauth/token
            # 사용자 정보를 조회할 수 있는 API 엔드포인트
            user-info-uri: https://kapi.kakao.com/v2/user/me
            # 사용자의 고유 식별자를 나타내는 프로필의 응답속성
            user-name-attribute: id

          # Naver OAuth2 Provider 설정
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

secret-key: "set_to_very_very_very_very_very_very_very_very_very_very_very_very_long_key"
# logging:
#   level:
#     root: info
#     "[org.springframework]": debug
